version: "3.3"
services:
  flask:
    build: ./server
    image: flask:v1
    working_dir: /code
    volumes:
      - ./server:/code
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes: 
      - ./redis:/redis.conf
    command: [ "redis-server", "/redis.conf" ]