version: "3.3"
services:
  flask:
    build: ./server
    image: flask:v3
    working_dir: /code
    volumes:
      - ./server:/code
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/redis.conf
    command: ["redis-server", "/redis.conf"]
  spark-master:
    image: spark
    build: ./spark
    command: standalone master
    hostname: spark-master
    expose:
      - 7077
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ./spark:/code
    depends_on: 
      - redis
  spark-worker1:
    image: spark
    command: standalone worker spark://spark-master:7077
    volumes:
      - ./spark:/code
    links:
      - spark-master
    depends_on:
      - spark-master
      - redis     
  spark-worker2:
    image: spark
    command: standalone worker spark://spark-master:7077
    volumes:
      - ./spark:/code
    links:
      - spark-master
    depends_on:
      - spark-master
      - redis     
  spark-main:
    image: spark
    command: python3 app.py
    volumes:
      - ./spark:/code
    depends_on:
      - spark-master
      - redis      
